// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcY4xQCHXpWiZ8qJULkhbQJSoEMjcvdkI',
    appId: '1:786699485546:web:fbfba55e4b546736202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    authDomain: 'multiservice-aa4e9.firebaseapp.com',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    measurementId: 'G-ECF206ZGC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMid5S8yz0TfDVLubWGjjPmihOIgiYyU',
    appId: '1:786699485546:android:b9d1654c55d6c776202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHIMqraMR-_g_wJWO1nxrR23WpCPgYf8',
    appId: '1:786699485546:ios:013d29f21ca6d7c4202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    androidClientId: '786699485546-0p54g8ssfggm8m0hv3mm29qoahloscqe.apps.googleusercontent.com',
    iosClientId: '786699485546-a58rromqh6rug0cq408lb5j1lc1r07da.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiserviceVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHIMqraMR-_g_wJWO1nxrR23WpCPgYf8',
    appId: '1:786699485546:ios:f91bfb1c12f37b96202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    androidClientId: '786699485546-0p54g8ssfggm8m0hv3mm29qoahloscqe.apps.googleusercontent.com',
    iosClientId: '786699485546-76n1t824j3cbgt1pg592st9dr323h3bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiserviceVendor.RunnerTests',
  );
}
